language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-crank' ]; then cd .. && eval "mv $currentfolder generator-crank" && cd generator-crank; fi

